### ISSUE TITLE
[Spring boot examples] : Migrate tutorials and examples to spring boot version 3

### ISSUE THREAD

**Issue by amirensit** [couchbase-examples/java-springboot-quickstart#50]
Hello.

I see examples and tutorials are still in spring boot 2.7 version.

Is there any intention to upgrade to version 3 ?

Best regards

**Comment by deniswsrosa** [comment]
Hi Choubani,

It is actually in progress, we should push the new version later this week.

**Comment by Shiroo77** [comment]
Hello, I would like to work on this issue. Migrating to spring 3.x. Can I work on this ? @deniswsrosa
